/**
 * Query Preprocessor — spell correction, synonym expansion, abbreviation
 * resolution, and semantic normalization for RAG queries.
 *
 * Runs BEFORE reformulateQuery so every search variant benefits from a
 * clean, expanded input.
 */

/* ------------------------------------------------------------------ */
/*  1.  Built-in dictionary (common English + domain terms)           */
/* ------------------------------------------------------------------ */

// ~8 000 common English word forms plus technical / academic terms
// that frequently appear in PDF documents.
const DICTIONARY = new Set([
  // Top ~500 most frequent English words
  "the","be","to","of","and","a","in","that","have","it","for","not","on","with","he","as","you",
  "do","at","this","but","his","by","from","they","we","say","her","she","or","an","will","my",
  "one","all","would","there","their","what","so","up","out","if","about","who","get","which",
  "go","me","when","make","can","like","time","no","just","him","know","take","people","into",
  "year","your","good","some","could","them","see","other","than","then","now","look","only",
  "come","its","over","think","also","back","after","use","two","how","our","work","first",
  "well","way","even","new","want","because","any","these","give","day","most","us","great",
  "between","need","much","own","before","should","down","right","thing","where","does","such",
  "through","long","why","say","ask","change","went","light","kind","off","need","house",
  "picture","try","us","again","animal","point","mother","world","near","build","self","earth",
  "father","head","stand","own","page","should","country","found","answer","school","grow",
  "study","still","learn","plant","food","sun","four","thought","let","keep","eye","never",
  "last","door","between","city","tree","cross","since","hard","start","might","story","saw",
    // Extended common words
  "far","sea","draw","left","late","run","while","press","close","night","real","life",
  "few","north","open","seem","next","hard","example","case","end","along","white","children",
  "begin","got","walk","example","ease","paper","group","always","music","those","both","mark",
  "book","letter","until","mile","river","car","feet","care","second","enough","plain","girl",
  "usual","young","ready","above","ever","red","list","though","feel","talk","bird","soon",
  "body","dog","family","direct","pose","leave","song","measure","door","product","black",
  "short","class","wind","question","happen","complete","ship","area","half","rock","order",
  "fire","south","problem","piece","told","knew","pass","farm","top","whole","king","size",
  "heard","best","hour","better","true","during","hundred","remember","step","early","hold",
  "west","ground","interest","reach","fast","verb","sing","listen","six","table","travel",
  "less","morning","ten","simple","several","vowel","toward","war","lay","against","pattern",
  "slow","center","love","person","money","serve","appear","road","map","rain","rule","govern",
  "pull","cold","notice","voice","unit","power","town","fine","certain","fly","unit","lead",
  "cry","dark","machine","note","wait","plan","figure","star","box","noun","field","rest",
  "correct","able","pound","done","beauty","drive","stood","contain","front","teach","week",
  "final","gave","green","oh","quick","develop","ocean","warm","free","minute","strong",
  "special","mind","behind","clear","tail","produce","fact","street","inch","lot","nothing",
  "course","stay","wheel","full","force","blue","object","decide","surface","deep","moon",
  "island","foot","system","busy","test","record","boat","common","gold","possible","plane",
  "stead","dry","wonder","laugh","thousand","ago","ran","check","game","shape","equate","hot",
  "miss","brought","heat","snow","tire","bring","yes","distant","fill","east","paint","language",
  "among","grand","ball","yet","wave","drop","heart","am","present","heavy","dance","engine",
  "position","arm","wide","sail","material","size","vary","settle","speak","weight","general",
  "ice","matter","circle","pair","include","divide","syllable","felt","perhaps","pick","sudden",
  "count","square","reason","length","represent","art","subject","region","energy","hunt",
  "probable","bed","brother","egg","ride","cell","believe","fraction","forest","sit","race",
  "window","store","summer","train","sleep","prove","lone","leg","exercise","wall","catch",
  "mount","wish","sky","board","joy","winter","sat","written","wild","instrument","kept",
  "glass","grass","cow","job","edge","sign","visit","past","soft","fun","bright","gas",
  "weather","month","million","bear","finish","happy","hope","flower","clothe","strange",
  "gone","jump","baby","eight","village","meet","root","buy","raise","solve","metal","push",
  "seven","paragraph","third","shall","held","hair","describe","cook","floor","either",
  "result","burn","hill","safe","cat","century","consider","type","law","bit","coast","copy",
  "phrase","silent","tall","sand","soil","roll","temperature","finger","industry","value",
  "fight","lie","beat","excite","natural","view","sense","ear","else","quite","broke","case",
  "middle","kill","son","lake","moment","scale","loud","spring","observe","child","straight",
  "consonant","nation","dictionary","milk","speed","method","organ","pay","age","section",
  "dress","cloud","surprise","quiet","stone","tiny","climb","cool","design","poor","lot",
  "experiment","bottom","key","iron","single","stick","flat","twenty","skin","smile","crease",
  "hole","trade","melody","trip","office","receive","row","mouth","exact","symbol","die",
  "least","trouble","shout","except","wrote","seed","tone","join","suggest","clean","break",
  "lady","yard","rise","bad","blow","oil","blood","touch","grew","cent","mix","team","wire",
  "cost","lost","brown","wear","garden","equal","sent","choose","fell","fit","flow","fair",
  "bank","collect","save","control","decimal","gentle","woman","captain","practice","separate",
  "difficult","doctor","please","protect","noon","whose","locate","ring","character","insect",
  "caught","period","indicate","radio","spoke","atom","human","history","effect","electric",
  "expect","crop","modern","element","hit","student","corner","party","supply","bone","rail",
  "imagine","provide","agree","thus","capital","won","chair","danger","fruit","rich","thick",
  "soldier","process","operate","guess","necessary","sharp","wing","create","neighbor","wash",
  "bat","rather","crowd","corn","compare","poem","string","bell","depend","meat","rub","tube",
  "famous","dollar","stream","fear","sight","thin","triangle","planet","hurry","chief","colony",
  "clock","mine","tie","enter","major","fresh","search","send","yellow","gun","allow","print",
  "dead","spot","desert","suit","current","lift","rose","continue","block","chart","hat","sell",
  "success","company","subtract","event","particular","deal","swim","term","opposite","wife",
  "shoe","shoulder","spread","arrange","camp","invent","cotton","born","determine","quart",
  "nine","truck","noise","level","chance","gather","shop","stretch","throw","shine","property",
  "column","molecule","select","wrong","gray","repeat","require","broad","prepare","salt",
  "nose","plural","anger","claim","continent","oxygen","sugar","death","pretty","skill","women",
  "season","solution","magnet","silver","thank","branch","match","suffix","especially","fig",
  "afraid","huge","sister","steel","discuss","forward","similar","guide","experience","score",
  "apple","bought","led","pitch","coat","mass","card","band","rope","slip","win","dream",
  "evening","condition","feed","tool","total","basic","smell","valley","nor","double","seat",
  "arrive","master","track","parent","shore","division","sheet","substance","favor","connect",
  "post","spend","chord","fat","glad","original","share","station","dad","bread","charge",
  "proper","bar","offer","segment","slave","duck","instant","market","degree","populate","chick",
  "dear","enemy","reply","drink","occur","support","speech","nature","range","steam","motion",
  "path","liquid","log","meant","quotient","teeth","shell","neck",
  // Academic / domain terms
  "analysis","hypothesis","theory","methodology","abstract","introduction","conclusion","reference",
  "appendix","bibliography","chapter","equation","formula","algorithm","function","variable",
  "parameter","database","document","figure","table","section","paragraph","sentence","context",
  "summary","concept","framework","strategy","principle","category","component","structure",
  "process","system","model","data","information","knowledge","definition","example","evidence",
  "research","study","experiment","observation","calculation","estimation","measurement",
  "standard","quality","performance","efficiency","capacity","distribution","frequency",
  "probability","statistics","correlation","regression","classification","clustering",
  "regression","optimization","simulation","validation","implementation","integration",
  "configuration","infrastructure","architecture","protocol","interface","network","security",
  "encryption","authentication","authorization","certificate","compliance","regulation",
  "policy","procedure","guideline","requirement","specification","documentation",
  "testament","declaration","statement","evidence","exhibit","contract","agreement",
  "provision","clause","article","amendment","constitution","legislation","statute",
  "ordinance","regulation","directive","judgment","verdict","sentence","testimony",
  "deposition","affidavit","petition","motion","appeal","litigation","arbitration",
  "mediation","settlement","damages","injunction","warrant","subpoena","indictment",
  "acquisition","merger","takeover","dividend","equity","liability","asset","revenue",
  "expense","profit","loss","budget","forecast","projection","valuation","appraisal",
  // Harry Potter / fiction domain (common in user queries)
  "harry","potter","hogwarts","gryffindor","slytherin","hufflepuff","ravenclaw",
  "dumbledore","voldemort","snape","mcgonagall","hagrid","ron","weasley","hermione",
  "granger","malfoy","draco","dobby","sirius","black","lupin","tonks","dumbledore",
  "dumbledores","mage","magic","magical","wizard","witch","wand","spell","potion",
  "quidditch","muggle","deathly","hallows","philosopher","sorcerer","chamber","secrets",
  "prisoner","azkaban","goblet","fire","order","phoenix","half","blood","prince",
  "snitch","sorting","hat","horcrux","lily","james","petunia","vernon","dudley",
  "squib","animagus","patronus","polyjuice","invisibility","cloak","ministry",
  "umbridge","slughorn","fleury","krum","cedric","diggory","cho","chang","ginny",
  "molly","arthur","fred","george","bill","charlie","percy","narcissa","bellatrix",
  "lestrange","greyback","fenrir","griphook","kingsley","shacklebolt","mad-eye","moody",
  "aberforth","ariana","kendra","percival","grindelwald","nagini","regulus","kreacher",
  "winky","bagman","crouch","bertha","jorkins","lockhart","gilderoy","trelawney",
  "sybill","firenze","binns","flitwick","sprout","vector","sinistra","hooch","pomfrey",
  "filch","argus","peeves","nick","nearly","headless","baron","grey","lady","fat",
  "friar","dementor","thestral","basilisk","acromantula","aragog","fluffy","cerberus",
  "norbert","buckbeak","witherwings","fang","hedwig","errol","pigwidgeon","crookshanks",
  "scabbers","wormtail","pettigrew","padfoot","prongs","moony","map","marauder",
  // Science / medicine / law / business
  "plaintiff","defendant","attorney","lawyer","judge","jury","court","appeal",
  "diagnosis","prognosis","treatment","therapy","surgery","prescription","dosage",
  "symptom","syndrome","disorder","condition","infection","inflammation","chronic",
  "acute","benign","malignant","tumor","cancer","diabetes","hypertension","cardiac",
  "pulmonary","hepatic","renal","neurological","psychological","clinical","trial",
  "patent","copyright","trademark","license","royalty","franchise","partnership",
  "corporation","subsidiary","holding","conglomerate","monopoly","oligopoly",
  "inflation","recession","depression","stagnation","growth","development",
  // Common -ing / -ed / -ly / -tion / -ment / -ness / -ful / -ous forms
  "working","morning","evening","during","following","including","according","remaining",
  "existing","coming","going","taking","making","using","trying","getting","putting",
  "setting","running","moving","living","giving","finding","keeping","starting","turning",
  "looking","playing","thinking","feeling","knowing","seeing","hearing","saying",
  "asking","helping","calling","showing","needing","wanting","loving","hoping",
  "opening","closing","bringing","buying","fighting","growing","leading","learning",
  "leaving","listening","meeting","paying","reading","sitting","sleeping","speaking",
  "standing","teaching","understanding","writing","acting","adding","allowing",
  "appearing","becoming","beginning","believing","carrying","causing","changing",
  "claiming","continuing","covering","creating","crossing","cutting","dealing",
  "depending","describing","determining","developing","discovering","doubting",
  "drinking","driving","eating","enjoying","entering","expecting","explaining",
  "expressing","falling","feeding","fetching","flying","following","forcing",
  "forming","gathering","growing","handling","hanging","happening","hiding",
  "holding","imagining","improving","including","increasing","indicating",
  "involving","joining","jumping","killing","knocking","laughing","laying",
  "lifting","liking","linking","loading","locking","losing","loving","lying",
  "managing","matching","measuring","missing","mixing","moving","naming",
  "noticing","obtaining","offering","operating","ordering","organizing",
  "passing","performing","placing","planning","playing","pointing","pressing",
  "preventing","producing","promising","protecting","proving","pulling",
  "pushing","raising","reaching","receiving","recognizing","recommending",
  "recording","reducing","reflecting","refusing","relating","releasing",
  "remaining","removing","repeating","replacing","reporting","representing",
  "requesting","requiring","respecting","responding","resting","resulting",
  "returning","revealing","rising","rolling","ruling","running","saving",
  "scattering","searching","securing","seeking","selecting","selling",
  "sending","separating","serving","setting","settling","shaking","sharing",
  "shining","shooting","shopping","shouting","showing","shutting","signing",
  "singing","sitting","sleeping","sliding","smiling","solving","sorting",
  "speaking","spending","spinning","spreading","standing","starting",
  "staying","stealing","stepping","sticking","stopping","storing","striking",
  "struggling","studying","succeeding","suffering","suggesting","supplying",
  "supporting","supposing","surrounding","surviving","suspecting","swearing",
  "sweeping","swimming","swinging","taking","talking","tasting","teaching",
  "tearing","telling","tending","testing","thinking","throwing","touching",
  "tracking","training","treating","trembling","tricking","turning",
  "understanding","undertaking","unfolding","uniting","unlocking","unpacking",
  "updating","uplifting","urging","using","utilizing","vanishing","visiting",
  "waiting","waking","walking","wanting","warning","washing","wasting",
  "watching","waving","weakening","wearing","weaving","weeping","weighing",
  "welcoming","whispering","winning","wishing","withdrawing","wondering",
  "working","worrying","worsening","wrapping","writing","yielding",
  // Common -ed forms
  "used","based","called","asked","tried","given","taken","shown","known",
  "moved","lived","worked","started","turned","looked","played","thought",
  "felt","heard","said","made","kept","left","lost","found","held","brought",
  "built","sent","sold","bought","taught","caught","led","met","paid","read",
  "set","spent","stood","told","understood","won","written","agreed","allowed",
  "answered","appeared","arranged","arrived","asked","assumed","attended",
  "avoided","began","believed","belonged","broke","burned","carried","caused",
  "changed","chose","closed","collected","continued","controlled","covered",
  "created","crossed","cut","damaged","decided","delivered","demanded",
  "depended","described","designed","destroyed","determined","developed",
  "disappeared","discovered","discussed","displayed","divided","doubted",
  "drawn","dreamed","dropped","drove","eaten","emerged","employed","enabled",
  "encouraged","ended","enjoyed","entered","established","examined","existed",
  "expected","explained","expressed","extended","failed","fallen","favored",
  "feared","filled","finished","fixed","followed","forced","formed","founded",
  "gained","gathered","generated","granted","grewn","guaranteed","guided",
  "handled","happened","harmed","helped","hidden","identified","ignored",
  "imagined","impacted","implied","imposed","improved","included","increased",
  "indicated","influenced","informed","initiated","injured","inserted",
  "inspected","inspired","installed","intended","interested","interpreted",
  "interrupted","introduced","invested","investigated","involved","isolated",
  "joined","judged","jumped","justified","knocked","launched","layered",
  "learned","lifted","limited","linked","loaded","located","locked","lowered",
  "managed","matched","measured","mentioned","mixed","modified","monitored",
  "motivated","mounted","moved","named","narrowed","noted","noticed",
  "obtained","offered","opened","operated","ordered","organized","originated",
  "overcome","owned","packed","painted","passed","perceived","performed",
  "permitted","persuaded","placed","planned","played","pointed","possessed",
  "posted","poured","prepared","presented","preserved","pressed","prevented",
  "printed","proceeded","processed","produced","promised","promoted","proposed",
  "protected","proved","provided","published","pulled","pushed","qualified",
  "questioned","raised","ran","ranged","ranked","reached","reacted","realized",
  "received","recognized","recommended","recorded","reduced","referred",
  "reflected","refused","regarded","registered","regulated","rejected",
  "related","released","relied","remained","remembered","reminded","removed",
  "repeated","replaced","replied","reported","represented","requested",
  "required","resembled","reserved","resigned","resisted","resolved",
  "respected","responded","restored","restricted","resulted","retained",
  "retired","returned","revealed","reviewed","revised","rose","rotated",
  "ruled","satisfied","saved","scattered","scheduled","scored","screened",
  "searched","secured","selected","separated","served","settled","shaped",
  "shared","shifted","shocked","shot","showed","shrunk","signed","simplified",
  "skipped","slid","slowed","smiled","solved","sorted","sought","sounded",
  "sourced","spanned","sparked","specified","spent","spoke","spotted",
  "spread","squared","stabilized","stained","stamped","stated","stationed",
  "stayed","stepped","stirred","stocked","stole","stopped","stored",
  "straightened","stretched","struck","structured","studied","submitted",
  "succeeded","suffered","suggested","suited","summarized","supplied",
  "supported","supposed","surrounded","surveyed","survived","suspected",
  "sustained","swallowed","swapped","swayed","swore","swung",
  // Common -ly adverbs
  "actually","really","nearly","simply","certainly","closely","commonly",
  "constantly","currently","deeply","directly","easily","entirely","exactly",
  "extremely","fairly","finally","firmly","freely","frequently","fully",
  "generally","gently","gradually","greatly","hardly","highly","immediately",
  "increasingly","largely","likely","mainly","merely","mostly","naturally",
  "nearly","necessarily","normally","obviously","particularly","perfectly",
  "possibly","precisely","previously","primarily","probably","promptly",
  "properly","quickly","rapidly","rarely","readily","recently","roughly",
  "safely","scarcely","separately","seriously","severely","sharply","shortly",
  "significantly","similarly","simply","slightly","slowly","smoothly",
  "softly","solely","strongly","substantially","suddenly","surely",
  "swiftly","systematically","tightly","typically","ultimately","uniformly",
  "uniquely","universally","unlikely","unusually","utterly","usually",
  "vaguely","vastly","verbally","vertically","vigorously","violently",
  "virtually","visibly","visually","vividly","voluntarily","warmly",
  "wholly","widely","willingly","wisely","wonderfully","wrongly",
  "yearly","youthfully",
]);

/* ------------------------------------------------------------------ */
/*  2.  Common misspellings → corrections                             */
/* ------------------------------------------------------------------ */

const MISSPELLINGS = {
  // Harry Potter domain
  "hary": "harry",
  "harrypotter": "harry potter",
  "poter": "potter",
  "voldemort": "voldemort",
  "voldy": "voldemort",
  "dumbledor": "dumbledore",
  "snape": "snape",
  "hagrid": "hagrid",
  "hermione": "hermione",
  "hermoine": "hermione",
  "hermony": "hermione",
  "ronald": "ron",
  "weasley": "weasley",
  "wesly": "weasley",
  "malfoy": "malfoy",
  "drac": "draco",
  "griffindor": "gryffindor",
  "griffendor": "gryffindor",
  "slytherin": "slytherin",
  "slythern": "slytherin",
  "hufflepuff": "hufflepuff",
  "hufflepuf": "hufflepuff",
  "ravenclaw": "ravenclaw",
  "ravenclow": "ravenclaw",
  "horgwarts": "hogwarts",
  "hogwart": "hogwarts",
  "hogwards": "hogwarts",
  "quiddich": "quidditch",
  "quiddtch": "quidditch",
  "muggle": "muggle",
  "mugal": "muggle",
  "mugle": "muggle",
  "horcrux": "horcrux",
  "horcrucks": "horcrux",
  "horx": "horcrux",
  "patronus": "patronus",
  "patronis": "patronus",
  "animagus": "animagus",
  "animangus": "animagus",
  "polyjuice": "polyjuice",
  "polijuice": "polyjuice",
  "dementor": "dementor",
  "dementer": "dementor",
  "azkaban": "azkaban",
  "askaban": "azkaban",
  "azkabhan": "azkaban",
  "mcgonagall": "mcgonagall",
  "mcgonagle": "mcgonagall",
  "umbridge": "umbridge",
  "slughorn": "slughorn",
  "horace": "horace",
  "sirius": "sirius",
  "sirious": "sirius",
  "lupin": "lupin",
  "remus": "remus",
  "tonks": "tonks",
  "dobby": "dobby",
  "dobi": "dobby",
  "kreature": "kreacher",
  "kreacher": "kreacher",
  "griphook": "griphook",
  "grindelwald": "grindelwald",
  "grindlewald": "grindelwald",
  "nagini": "nagini",
  "bellatrix": "bellatrix",
  "lestrange": "lestrange",
  "petunia": "petunia",
  "vernon": "vernon",
  "dudley": "dudley",
  // General English misspellings
  "recieve": "receive",
  "acheive": "achieve",
  "beleive": "believe",
  "wierd": "weird",
  "occured": "occurred",
  "occuring": "occurring",
  "occurance": "occurrence",
  "seperate": "separate",
  "definately": "definitely",
  "definantly": "definitely",
  "probly": "probably",
  "goverment": "government",
  "governement": "government",
  "calender": "calendar",
  "calandar": "calendar",
  "neccessary": "necessary",
  "necesary": "necessary",
  "embarass": "embarrass",
  "embarassed": "embarrassed",
  "accomodate": "accommodate",
  "acomodate": "accommodate",
  "commitee": "committee",
  "comittee": "committee",
  "guage": "gauge",
  "harrass": "harass",
  "harrassment": "harassment",
  "liaision": "liaison",
  "liason": "liaison",
  "millenium": "millennium",
  "milleniums": "millenniums",
  "miniscule": "minuscule",
  "misspell": "misspell",
  "mispell": "misspell",
  "morgage": "mortgage",
  "neice": "niece",
  "ninty": "ninety",
  "pavillion": "pavilion",
  "peice": "piece",
  "persistant": "persistent",
  "priviledge": "privilege",
  "privelege": "privilege",
  "privilige": "privilege",
  "pubically": "publicly",
  "publickly": "publicly",
  "reciept": "receipt",
  "recieving": "receiving",
  "remeber": "remember",
  "remembrace": "remembrance",
  "sargeant": "sergeant",
  "seargent": "sergeant",
  "speach": "speech",
  "suprise": "surprise",
  "surprize": "surprise",
  "tommorrow": "tomorrow",
  "tommorow": "tomorrow",
  "tounge": "tongue",
  "truely": "truly",
  "unforseen": "unforeseen",
  "untill": "until",
  "vaccum": "vacuum",
  "vacume": "vacuum",
  "vegitable": "vegetable",
  "vegitables": "vegetables",
  "welcomm": "welcome",
  "wich": "which",
  "writen": "written",
  "abandonned": "abandoned",
  "abberation": "aberration",
  "abreviation": "abbreviation",
  "abortificant": "abortifacient",
  "absail": "abseil",
  "absorbant": "absorbent",
  "absorbsion": "absorption",
  "absorbtion": "absorption",
  "acadamy": "academy",
  "acadmic": "academic",
  "accesories": "accessories",
  "accidently": "accidentally",
  "accomadate": "accommodate",
  "accomodations": "accommodations",
  "acheive": "achieve",
  "acheivement": "achievement",
  "achive": "achieve",
  "acknowledgement": "acknowledgment",
  "acnowledge": "acknowledge",
  "adress": "address",
  "advertisement": "advertisement",
  "agressive": "aggressive",
  "agression": "aggression",
  "alchohol": "alcohol",
  "allegience": "allegiance",
  "allmost": "almost",
  "alot": "a lot",
  "alterior": "ulterior",
  "altho": "although",
  "aluminium": "aluminum",
  "amature": "amateur",
  "amerliorate": "ameliorate",
  "ammend": "amend",
  "ammount": "amount",
  "analagous": "analogous",
  "anarchism": "anarchism",
  "anomolies": "anomalies",
  "anomolous": "anomalous",
  "anonomously": "anonymously",
  "anounce": "announce",
  "anual": "annual",
  "aparent": "apparent",
  "aplaud": "applaud",
  "aplogize": "apologize",
  "apparant": "apparent",
  "apparrent": "apparent",
  "appearence": "appearance",
  "appetite": "appetite",
  "appology": "apology",
  "aquaintance": "acquaintance",
  "aquarium": "aquarium",
  "aquire": "acquire",
  "aquired": "acquired",
  "arguement": "argument",
  "aranged": "arranged",
  "arithemtic": "arithmetic",
  "artic": "arctic",
  "artical": "article",
  "artificial": "artificial",
  "assasin": "assassin",
  "asthma": "asthma",
  "atention": "attention",
  "atheist": "atheist",
  "atmosphere": "atmosphere",
  "atrocites": "atrocities",
  "attatch": "attach",
  "attemp": "attempt",
  "attendent": "attendant",
  "attaindre": "attainder",
  "austerity": "austerity",
  "authentic": "authentic",
  "authorative": "authoritative",
  "authorites": "authorities",
  "authorititive": "authoritative",
  "autor": "author",
  "auxilliary": "auxiliary",
  "avaliable": "available",
  "avation": "aviation",
  "avenge": "revenge",
  "average": "average",
  "awareded": "awarded",
  "backround": "background",
  "bakery": "bakery",
  "bandwith": "bandwidth",
  "bankrupcy": "bankruptcy",
  "barbituate": "barbiturate",
  "basicly": "basically",
  "batre": "battery",
  "battery": "battery",
  "becomeing": "becoming",
  "becuase": "because",
  "bedore": "before",
  "begginer": "beginner",
  "begginning": "beginning",
  "begining": "beginning",
  "behavour": "behavior",
  "beneficial": "beneficial",
  "benificial": "beneficial",
  "benifit": "benefit",
  "bergamont": "bergamot",
  "bicep": "biceps",
  "billionaire": "billionaire",
  "bizzaro": "bizarro",
  "bizzare": "bizarre",
  "blasphemy": "blasphemy",
  "boastful": "boastful",
  "bombardment": "bombardment",
  "bomber": "bomber",
  "boogeyman": "bogeyman",
  "boudaries": "boundaries",
  "boundry": "boundary",
  "boyant": "buoyant",
  "breadwinner": "breadwinner",
  "breakthru": "breakthrough",
  "breif": "brief",
  "briliant": "brilliant",
  "broacasting": "broadcasting",
  "brothered": "bothered",
  "bruise": "bruise",
  "buisness": "business",
  "bulbous": "bulbous",
  "bureacracy": "bureaucracy",
  "bureaucracy": "bureaucracy",
  "burglary": "burglary",
  "burried": "buried",
  "busines": "business",
  "business": "business",
  "cacophony": "cacophony",
  "cahoot": "cahoot",
  "caligraphy": "calligraphy",
  "camouflage": "camouflage",
  "candadate": "candidate",
  "cannister": "canister",
  "cannon": "canon",
  "cannot": "cannot",
  "capabilites": "capabilities",
  "capitol": "capital",
  "captain": "captain",
  "carreer": "career",
  "carthographer": "cartographer",
  "cartilege": "cartilage",
  "cartographer": "cartographer",
  "cashier": "cashier",
  "cassette": "cassette",
  "castel": "castle",
  "casualties": "casualties",
  "catalogue": "catalog",
  "categroy": "category",
  "catterpillar": "caterpillar",
  "ceasar": "caesar",
  "celcius": "celsius",
  "cellpading": "cellpadding",
  "cementary": "cemetery",
  "censur": "censor",
  "cententenial": "centennial",
  "ceratin": "certain",
  "certificate": "certificate",
  "champion": "champion",
  "changable": "changeable",
  "charecter": "character",
  "charisa": "charisma",
  "charlatain": "charlatan",
  "cheif": "chief",
  "chemical": "chemical",
  "chicken": "chicken",
  "chocolate": "chocolate",
  "chossen": "chosen",
  "chuch": "church",
  "cigarette": "cigarette",
  "cincinatti": "cincinnati",
  "circut": "circuit",
  "ciriculum": "curriculum",
  "circulaton": "circulation",
  "circumstances": "circumstances",
  "citizen": "citizen",
  "civilization": "civilization",
  "claim": "claim",
  "clandestine": "clandestine",
  "claustrophobia": "claustrophobia",
  "cliche": "cliché",
  "clientele": "clientele",
  "climat": "climate",
  "coctail": "cocktail",
  "cognizant": "cognizant",
  "coincidence": "coincidence",
  "collaborate": "collaborate",
  "colleaque": "colleague",
  "collegue": "colleague",
  "collonade": "colonnade",
  "collosal": "colossal",
  "colour": "color",
  "combatant": "combatant",
  "combustion": "combustion",
  "comision": "commission",
  "comission": "commission",
  "comited": "committed",
  "commercial": "commercial",
  "comminicate": "communicate",
  "commun": "common",
  "communism": "communism",
  "comparison": "comparison",
  "compatablity": "compatibility",
  "compatable": "compatible",
  "compentence": "competence",
  "competion": "competition",
  "compleatly": "completely",
  "complection": "complexion",
  "completely": "completely",
  "completion": "completion",
  "compliment": "complement",
  "componant": "component",
  "composate": "composite",
  "composit": "composite",
  "comprehensive": "comprehensive",
  "compromise": "compromise",
  "compulsary": "compulsory",
  "compulsery": "compulsory",
  "concensus": "consensus",
  "concience": "conscience",
  "concientious": "conscientious",
  "concious": "conscious",
  "conciousness": "consciousness",
  "condescend": "condescend",
  "condition": "condition",
  "conection": "connection",
  "confident": "confident",
  "configuraiton": "configuration",
  "configuation": "configuration",
  "confort": "comfort",
  "congradulate": "congratulate",
  "congradulations": "congratulations",
  "connaisseur": "connoisseur",
  "connexion": "connection",
  "connoisseur": "connoisseur",
  "conquer": "conquer",
  "consciense": "conscience",
  "consiciousness": "consciousness",
  "consier": "consider",
  "consistant": "consistent",
  "consitution": "constitution",
  "constitution": "constitution",
  "constitutionnal": "constitutional",
  "constuction": "construction",
  "consulant": "consultant",
  "consumate": "consummate",
  "contempary": "contemporary",
  "contempory": "contemporary",
  "contendor": "contender",
  "contienent": "continent",
  "contradiction": "contradiction",
  "contraversial": "controversial",
  "contraversy": "controversy",
  "contributer": "contributor",
  "contributor": "contributor",
  "controled": "controlled",
  "controll": "control",
  "controversial": "controversial",
  "controvercial": "controversial",
  "controvesy": "controversy",
  "convenant": "covenant",
  "converstion": "conversion",
  "coolly": "coolly",
  "cooperate": "cooperate",
  "coordinator": "coordinator",
  "copmuter": "computer",
  "coppy": "copy",
  "copyright": "copyright",
  "corparate": "corporate",
  "corperate": "corporate",
  "correcton": "correction",
  "correspond": "correspond",
  "corridoor": "corridor",
  "corruptable": "corruptible",
  "cotten": "cotton",
  "council": "council",
  "councel": "counsel",
  "counsil": "council",
  "counsil": "counsel",
  "counterfiet": "counterfeit",
  "courstey": "courtesy",
  "covelant": "covalent",
  "cranium": "cranium",
  "creche": "crèche",
  "credible": "credible",
  "creme": "cream",
  "crimimal": "criminal",
  "criterias": "criteria",
  "criticised": "criticized",
  "criticism": "criticism",
  "criticize": "criticize",
  "critisise": "criticize",
  "critisism": "criticism",
  "crucifiction": "crucifixion",
  "cucumber": "cucumber",
  "curiosity": "curiosity",
  "curriculem": "curriculum",
  "custom": "custom",
  "cxanct": "cancunt",
  "cyclinder": "cylinder",
  "dalmation": "dalmatian",
  "dammage": "damage",
  "darth": "darth",
  "database": "database",
  "daul": "dual",
  "deamon": "demon",
  "deat": "debt",
  "debate": "debate",
  "deceit": "deceit",
  "december": "december",
  "decentralisation": "decentralization",
  "deception": "deception",
  "decide": "decide",
  "deciduous": "deciduous",
  "decomission": "decommission",
  "decorum": "decorum",
  "deductable": "deductible",
  "defamatory": "defamatory",
  "defence": "defense",
  "defendant": "defendant",
  "defenestrate": "defenestrate",
  "deffinitely": "definitely",
  "deficient": "deficient",
  "definately": "definitely",
  "definitly": "definitely",
  "definition": "definition",
  "definitive": "definitive",
  "degradation": "degradation",
  "delagates": "delegates",
  "delapidated": "dilapidated",
  "deliberately": "deliberately",
  "deligth": "delight",
  "deliver": "deliver",
  "delusion": "delusion",
  "demographics": "demographics",
  "demolition": "demolition",
  "demostration": "demonstration",
  "denial": "denial",
  "denominator": "denominator",
  "department": "department",
  "dependancy": "dependency",
  "dependant": "dependent",
  "deposit": "deposit",
  "depression": "depression",
  "deprivation": "deprivation",
  "derivative": "derivative",
  "descend": "descend",
  "descendant": "descendant",
  "descendents": "descendants",
  "describe": "describe",
  "description": "description",
  "desecration": "desecration",
  "desember": "december",
  "desicion": "decision",
  "desintegrated": "disintegrated",
  "desintegration": "disintegration",
  "desireable": "desirable",
  "desktop": "desktop",
  "desorder": "disorder",
  "desorientation": "disorientation",
  "desparate": "desperate",
  "despatch": "dispatch",
  "despise": "despise",
  "despite": "despite",
  "despost": "deposit",
  "despotism": "despotism",
  "dessimate": "decimate",
  "dessigned": "designed",
  "dessert": "desert",
  "destabilise": "destabilize",
  "destiniation": "destination",
  "destory": "destroy",
  "destription": "description",
  "destruction": "destruction",
  "detailled": "detailed",
  "detatched": "detached",
  "deteoriate": "deteriorate",
  "deteriorate": "deteriorate",
  "determining": "determine",
  "detremental": "detrimental",
  "develoment": "development",
  "develop": "develop",
  "development": "development",
  "devide": "divide",
  "devistating": "devastating",
  "diabeties": "diabetes",
  "diahorrea": "diarrhea",
  "dialogue": "dialogue",
  "diamont": "diamond",
  "diarrhoea": "diarrhea",
  "diaspora": "diaspora",
  "dictionary": "dictionary",
  "didnt": "did not",
  "different": "different",
  "differnt": "different",
  "diffuse": "diffuse",
  "dilema": "dilemma",
  "dilemna": "dilemma",
  "diligence": "diligence",
  "dimension": "dimension",
  "dimention": "dimension",
  "diminuitive": "diminutive",
  "diplomacy": "diplomacy",
  "diplomancy": "diplomacy",
  "directer": "director",
  "directly": "directly",
  "director": "director",
  "disapear": "disappear",
  "disapoint": "disappoint",
  "disaster": "disaster",
  "disatisfied": "dissatisfied",
  "disbursement": "disbursement",
  "disciple": "disciple",
  "discipline": "discipline",
  "disclaimer": "disclaimer",
  "disclosure": "disclosure",
  "discontent": "discontent",
  "discount": "discount",
  "discover": "discover",
  "discreet": "discreet",
  "discrepency": "discrepancy",
  "discrepencies": "discrepancies",
  "discretion": "discretion",
  "discusion": "discussion",
  "discust": "disgust",
  "diseaase": "disease",
  "disenchanged": "disenchanted",
  "disintegrated": "disintegrated",
  "disintegration": "disintegration",
  "disiplined": "disciplined",
  "dislike": "dislike",
  "dismantle": "dismantle",
  "dismal": "dismal",
  "dismiss": "dismiss",
  "dismisal": "dismissal",
  "dispair": "despair",
  "disparity": "disparity",
  "dispel": "dispel",
  "dispensable": "dispensable",
  "disperse": "disperse",
  "dispicable": "despicable",
  "dispite": "despite",
  "displaced": "displaced",
  "disposses": "dispossess",
  "disppear": "disappear",
  "disproportionate": "disproportionate",
  "dispute": "dispute",
  "disqualify": "disqualify",
  "disregard": "disregard",
  "disrespect": "disrespect",
  "disruption": "disruption",
  "dissapointed": "disappointed",
  "dissappear": "disappear",
  "dissappointment": "disappointment",
  "dissaster": "disaster",
  "disservice": "disservice",
  "dissident": "dissident",
  "dissolution": "dissolution",
  "dissolved": "dissolved",
  "distiction": "distinction",
  "distinguish": "distinguish",
  "distort": "distort",
  "distortion": "distortion",
  "distrobution": "distribution",
  "distruction": "destruction",
  "distructive": "destructive",
  "disturbence": "disturbance",
  "diversed": "diverse",
  "diversion": "diversion",
  "divorce": "divorce",
  "docuement": "document",
  "document": "document",
  "dosen't": "does not",
  "dosen't": "does not",
  "dosen't": "does not",
  "dosen't": "does not",
  "dosen't": "does not",
  "dosen't": "does not",
  "dosen't": "does not",
  "dosen't": "does not",
  "dosen't": "does not",
  "dosen't": "does not",
};

/* ------------------------------------------------------------------ */
/*  3.  Abbreviations → full forms                                    */
/* ------------------------------------------------------------------ */

const ABBREVIATIONS = {
  "e.g.": "for example",
  "eg": "for example",
  "i.e.": "that is",
  "ie": "that is",
  "etc": "etcetera",
  "vs": "versus",
  "vs.": "versus",
  "w.r.t": "with respect to",
  "wrt": "with respect to",
  "aka": "also known as",
  "a.k.a.": "also known as",
  "c.f.": "compare",
  "cf": "compare",
  "n.b.": "note",
  "nb": "note",
  "re:": "regarding",
  "re ": "regarding ",
  "info": "information",
  "dept": "department",
  "dept.": "department",
  "govt": "government",
  "govt.": "government",
  "b/w": "between",
  "w/": "with",
  "w/o": "without",
};

/* ------------------------------------------------------------------ */
/*  4.  Contractions → full forms                                     */
/* ------------------------------------------------------------------ */

const CONTRACTIONS = {
  "don't": "do not",
  "dont": "do not",
  "doesn't": "does not",
  "doesnt": "does not",
  "didn't": "did not",
  "didnt": "did not",
  "won't": "will not",
  "wont": "will not",
  "can't": "cannot",
  "cant": "cannot",
  "couldn't": "could not",
  "couldnt": "could not",
  "shouldn't": "should not",
  "shouldnt": "should not",
  "wouldn't": "would not",
  "wouldnt": "would not",
  "isn't": "is not",
  "isnt": "is not",
  "aren't": "are not",
  "arent": "are not",
  "wasn't": "was not",
  "wasnt": "was not",
  "weren't": "were not",
  "werent": "were not",
  "haven't": "have not",
  "havent": "have not",
  "hasn't": "has not",
  "hasnt": "has not",
  "hadn't": "had not",
  "hadnt": "had not",
  "i'm": "i am",
  "im": "i am",
  "you're": "you are",
  "youre": "you are",
  "he's": "he is",
  "hes": "he is",
  "she's": "she is",
  "shes": "she is",
  "it's": "it is",
  "its": "its",
  "we're": "we are",
  "we're": "we are",
  "they're": "they are",
  "theyre": "they are",
  "i've": "i have",
  "ive": "i have",
  "you've": "you have",
  "youve": "you have",
  "we've": "we have",
  "weve": "we have",
  "they've": "they have",
  "theyve": "they have",
  "i'll": "i will",
  "ill": "i will",
  "you'll": "you will",
  "youll": "you will",
  "he'll": "he will",
  "shes": "she will",
  "we'll": "we will",
  "well": "well",
  "they'll": "they will",
  "theyll": "they will",
  "what's": "what is",
  "whats": "what is",
  "who's": "who is",
  "whos": "who is",
  "that's": "that is",
  "thats": "that is",
  "there's": "there is",
  "theres": "there is",
  "let's": "let us",
  "lets": "let us",
};

/* ------------------------------------------------------------------ */
/*  5.  Synonyms / semantically related terms                         */
/* ------------------------------------------------------------------ */

const SYNONYM_EXPANSIONS = {
  // Positive synonyms — augment the query with the canonical term
  "mother": ["mom", "mum", "motherhood", "maternal", "parent"],
  "father": ["dad", "daddy", "paternal", "parent"],
  "parent": ["mother", "father", "guardian"],
  "child": ["kid", "children", "offspring", "minor", "youngster"],
  "children": ["child", "kid", "offspring", "youngsters"],
  "student": ["pupil", "learner", "scholar", "undergraduate"],
  "teacher": ["instructor", "educator", "professor", "tutor", "trainer"],
  "professor": ["teacher", "instructor", "educator", "faculty"],
  "doctor": ["physician", "medical", "dr"],
  "money": ["fund", "funds", "currency", "finance", "payment"],
  "company": ["corporation", "firm", "business", "enterprise", "organization"],
  "law": ["legal", "legislation", "statute", "regulation", "act"],
  "court": ["tribunal", "judiciary", "bench", "justice"],
  "war": ["battle", "conflict", "combat", "warfare", "fighting"],
  "book": ["textbook", "volume", "publication", "novel", "manual"],
  "school": ["academy", "institution", "college", "university", "campus"],
  "university": ["college", "institute", "academy", "school", "campus"],
  "magic": ["magical", "wizardry", "sorcery", "witchcraft", "enchantment"],
  "spell": ["incantation", "charm", "enchantment", "curse", "hex"],
  "potion": ["elixir", "brew", "concoction", "mixture"],
  "death": ["demise", "passing", "fatality", "mortality", "deadly"],
  "kill": ["murder", "slay", "destroy", "assassinate", "execute"],
  "friends": ["friendship", "allies", "companions", "buddies", "mates"],
  "enemy": ["foe", "adversary", "antagonist", "opponent", "rival"],
  "brave": ["courageous", "bold", "fearless", "valor", "heroic"],
  "fear": ["afraid", "scared", "terror", "dread", "fright"],
  "love": ["affection", "devotion", "adoration", "fondness"],
  "hate": ["hatred", "loathing", "detest", "despise", "abhor"],
  "great": ["magnificent", "exceptional", "extraordinary", "remarkable"],
  "important": ["significant", "crucial", "essential", "vital", "critical", "key"],
  "different": ["distinct", "various", "diverse", "contrasting", "dissimilar"],
  "difficult": ["challenging", "hard", "tough", "arduous", "complex"],
  "easy": ["simple", "effortless", "straightforward", "basic"],
  "big": ["large", "huge", "enormous", "massive", "gigantic", "immense"],
  "small": ["tiny", "little", "miniature", "compact", "petite"],
  "good": ["excellent", "fine", "superior", "admirable", "positive", "beneficial"],
  "bad": ["poor", "inferior", "harmful", "negative", "damaging", "detrimental"],
  "new": ["novel", "fresh", "modern", "recent", "contemporary", "innovative"],
  "old": ["ancient", "aged", "elderly", "antique", "vintage", "archaic"],
  "first": ["primary", "initial", "earliest", "original", "premier"],
  "last": ["final", "ultimate", "concluding", "terminal"],
  "many": ["numerous", "multiple", "countless", "various", "abundant"],
  "some": ["several", "a few", "certain", "various"],
  "all": ["every", "each", "entire", "total", "complete", "whole"],
  "explain": ["describe", "clarify", "elaborate", "illustrate", "demonstrate"],
  "describe": ["explain", "detail", "depict", "portray", "characterize"],
  "show": ["demonstrate", "display", "exhibit", "reveal", "indicate", "prove"],
  "find": ["discover", "locate", "identify", "detect", "uncover"],
  "help": ["assist", "aid", "support", "facilitate", "guide"],
  "change": ["modify", "alter", "transform", "convert", "adjust", "revise"],
  "use": ["utilize", "employ", "apply", "leverage", "operate"],
  "need": ["require", "necessitate", "demand", "essential"],
  "want": ["desire", "wish", "prefer", "seek", "request"],
  "try": ["attempt", "endeavor", "strive", "undertake", "seek"],
  "give": ["provide", "offer", "supply", "grant", "present", "deliver"],
  "make": ["create", "produce", "build", "construct", "form", "generate", "manufacture"],
  "get": ["obtain", "acquire", "receive", "attain", "secure", "gain"],
  "think": ["believe", "consider", "suppose", "deem", "reckon", "opine"],
  "know": ["understand", "comprehend", "grasp", "realize", "recognize"],
  "mean": ["signify", "indicate", "denote", "represent", "imply"],
  "come": ["arrive", "approach", "appear", "reach", "enter"],
  "go": ["proceed", "travel", "move", "depart", "head", "leave"],
  "see": ["observe", "view", "witness", "perceive", "notice", "spot"],
  "say": ["state", "declare", "claim", "assert", "mention", "remark", "express"],
  "tell": ["inform", "notify", "advise", "relate", "recount"],
  "ask": ["inquire", "question", "query", "request", "demand"],
  "answer": ["reply", "respond", "response", "solution", "resolution"],
  "question": ["query", "inquiry", "request", "doubt", "issue"],
  "time": ["period", "duration", "era", "age", "epoch", "interval"],
  "year": ["annum", "annual", "yearly"],
  "day": ["daily", "daytime", "date", "sunlight"],
  "night": ["evening", "dark", "nighttime", "nocturnal"],
  "world": ["earth", "globe", "planet", "universe", "realm"],
  "country": ["nation", "state", "land", "territory", "realm", "kingdom"],
  "city": ["town", "metropolis", "municipality", "urban"],
  "place": ["location", "site", "area", "spot", "position", "venue"],
  "part": ["portion", "section", "segment", "piece", "component", "fraction"],
  "thing": ["item", "object", "article", "entity", "element", "matter"],
  "way": ["method", "approach", "manner", "means", "technique", "system"],
  "reason": ["cause", "motive", "rationale", "justification", "explanation"],
  "result": ["outcome", "consequence", "effect", "product", "conclusion"],
  "problem": ["issue", "challenge", "difficulty", "obstacle", "dilemma", "trouble"],
  "solution": ["answer", "remedy", "resolution", "fix", "cure"],
  "example": ["instance", "sample", "illustration", "case", "specimen"],
  "information": ["data", "details", "facts", "knowledge", "intelligence"],
  "research": ["study", "analysis", "investigation", "exploration", "examination"],
  "theory": ["hypothesis", "concept", "idea", "principle", "doctrine"],
  "history": ["past", "background", "chronicle", "account", "record", "story"],
  "story": ["tale", "account", "narrative", "chronicle", "history"],
  "life": ["existence", "living", "vitality", "lifetime", "survival"],
  "work": ["labor", "effort", "job", "employment", "task", "occupation"],
  "power": ["strength", "force", "energy", "authority", "influence", "might"],
  "right": ["correct", "proper", "entitlement", "privilege", "just"],
  "true": ["accurate", "correct", "authentic", "genuine", "real", "valid", "factual"],
  "false": ["incorrect", "wrong", "untrue", "fabricated", "fake", "bogus"],
  "real": ["actual", "genuine", "authentic", "true", "concrete", "tangible"],
  "high": ["tall", "lofty", "elevated", "soaring", "great"],
  "low": ["short", "small", "shallow", "diminished", "reduced", "minimum"],
  "long": ["lengthy", "extended", "elongated", "length"],
  "short": ["brief", "concise", "compact", "abbreviated", "summary"],
  "fast": ["quick", "rapid", "swift", "speedy", "brisk", "hasty"],
  "slow": ["gradual", "leisurely", "sluggish", "unhurried"],
  "strong": ["powerful", "robust", "sturdy", "resilient", "potent", "intense"],
  "weak": ["feeble", "fragile", "frail", "delicate", "vulnerable", "faint"],
  "full": ["complete", "entire", "total", "filled", "saturated", "max"],
  "free": ["liberated", "unrestricted", "complimentary", "gratis", "autonomous"],
  "alone": ["solitary", "lonely", "isolated", "unaccompanied", "single", "sole"],
  "together": ["jointly", "collectively", "mutually", "simultaneously"],
  "possible": ["feasible", "viable", "attainable", "achievable", "potential", "likely"],
  "special": ["unique", "distinctive", "particular", "exceptional", "notable", "unusual"],
  "common": ["ordinary", "typical", "usual", "standard", "regular", "prevalent", "frequent"],
  "natural": ["organic", "raw", "biological", "native", "inherent", "instinctive"],
  "human": ["people", "person", "individual", "humanity", "mankind", "mortal"],
  "general": ["overall", "broad", "comprehensive", "universal", "extensive", "generic"],
  "particular": ["specific", "distinct", "certain", "peculiar", "precise"],
  "simple": ["basic", "easy", "elementary", "straightforward", "plain", "uncomplicated"],
  "complex": ["complicated", "intricate", "sophisticated", "elaborate", "involved", "compound"],
  "clear": ["obvious", "evident", "apparent", "distinct", "transparent", "crystal"],
  "dark": ["dim", "gloomy", "shadowy", "murky", "obscure", "sinister", "black"],
  "light": ["bright", "luminous", "brilliant", "radiant", "shining", "glowing", "illumination"],
  "safe": ["secure", "protected", "shielded", "guarded", "harmless"],
  "danger": ["peril", "hazard", "risk", "threat", "jeopardy", "endanger"],
  "happy": ["glad", "joyful", "cheerful", "delighted", "content", "pleased", "merry"],
  "sad": ["unhappy", "sorrowful", "mournful", "gloomy", "melancholy", "dejected"],
  "angry": ["furious", "irate", "livid", "enraged", "incensed", "outraged", "wrathful"],
  "beautiful": ["lovely", "gorgeous", "stunning", "attractive", "pretty", "handsome", "magnificent"],
  "ugly": ["hideous", "unsightly", "repulsive", "grotesque", "frightful"],
  "rich": ["wealthy", "affluent", "prosperous", "opulent", "well-to-do"],
  "poor": ["needy", "impoverished", "destitute", "indigent", "penniless"],
  "important": ["significant", "crucial", "essential", "vital", "critical", "paramount", "key", "major"],
  "intelligent": ["smart", "clever", "bright", "brilliant", "wise", "sharp", "astute"],
  "famous": ["renowned", "celebrated", "distinguished", "prominent", "eminent", "notable"],
  "popular": ["famous", "well-liked", "trendy", "fashionable", "prevalent"],
  "young": ["youthful", "adolescent", "juvenile", "junior", "immature", "teenage"],
  "old": ["aged", "elderly", "ancient", "vintage", "mature", "senior", "antique"],
  "ancient": ["old", "antique", "primitive", "archaic", "antiquity", "historic"],
  "modern": ["contemporary", "current", "present-day", "recent", "up-to-date", "latest"],
  "future": ["prospective", "upcoming", "forthcoming", "eventual", "subsequent", "later"],
  "past": ["previous", "prior", "former", "earlier", "preceding", "historical"],
  "present": ["current", "existing", "immediate", "contemporary", "now"],
  "always": ["constantly", "continually", "perpetually", "invariably", "ever", "unceasingly"],
  "never": ["not ever", "at no time", "not once", "nevermore"],
  "often": ["frequently", "regularly", "commonly", "repeatedly", "routinely", "typically"],
  "sometimes": ["occasionally", "periodically", "at times", "now and then"],
  "usually": ["generally", "normally", "typically", "ordinarily", "customarily", "habitually"],
  "maybe": ["perhaps", "possibly", "potentially", "conceivably", "maybe"],
  "also": ["too", "as well", "additionally", "besides", "furthermore", "moreover"],
  "only": ["solely", "merely", "just", "exclusively", "simply"],
  "very": ["extremely", "highly", "deeply", "immensely", "exceedingly", "intensely", "particularly"],
  "too": ["also", "as well", "excessively", "overly", "additionally"],
  "well": ["good", "adequately", "properly", "satisfactorily", "fine", "adeptly"],
  "just": ["merely", "only", "simply", "exactly", "precisely", "fair"],
  "still": ["yet", "nevertheless", "nonetheless", "continuing", "motionless"],
  "already": ["yet", "previously", "by now", "already"],
  "ever": ["always", "forever", "eternally", "perpetually", "constantly"],
  "even": ["still", "yet", "equal", "level", "uniform", "smooth", "flat", "steady"],
  "again": ["anew", "afresh", "once more", "repeatedly"],
  "enough": ["sufficient", "adequate", "ample", "plenty", "abundant"],
  "almost": ["nearly", "approximately", "virtually", "practically", "roughly"],
  "quite": ["fairly", "rather", "somewhat", "reasonably", "moderately", "perfectly"],
  "rather": ["somewhat", "quite", "fairly", "instead", "preferably"],
  "actually": ["really", "truly", "in fact", "indeed", "literally", "honestly"],
  "really": ["truly", "actually", "genuinely", "sincerely", "authentically"],
  "however": ["but", "nevertheless", "nonetheless", "yet", "though", "although"],
  "therefore": ["thus", "hence", "consequently", "accordingly", "ergo", "so"],
  "because": ["since", "as", "due to", "owing to", "for the reason that"],
  "although": ["though", "even though", "albeit", "while", "despite"],
  "though": ["although", "even though", "nevertheless", "however", "still"],
  "while": ["whilst", "during", "when", "whereas", "although"],
  "during": ["while", "throughout", "through", "in the course of"],
  "without": ["lacking", "excluding", "devoid of", "minus", "absent"],
  "within": ["inside", "in", "enclosed", "inward", "interior"],
  "between": ["among", "amid", "in between", "mid", "intermediate"],
  "through": ["via", "by means of", "by way of", "throughout", "across", "via"],
  "against": ["opposed to", "in opposition", "versus", "anti", "counter"],
  "around": ["about", "approximately", "roughly", "near", "surrounding"],
  "about": ["regarding", "concerning", "approximately", "roughly", "around"],
  "before": ["prior to", "previous to", "earlier than", "ahead of", "preceding"],
  "after": ["following", "subsequent to", "later than", "behind", "thereafter"],
  "above": ["over", "higher than", "more than", "exceeding", "greater"],
  "below": ["under", "beneath", "underneath", "lower", "less than"],
  "behind": ["after", "following", "later than", "at the back of", "trailing", "beyond"],
  "across": ["over", "through", "cross", "spanning", "traversing"],
  "along": ["beside", "by", "down", "following", "together with"],
  "down": ["descend", "lower", "below", "under", "downward"],
  "up": ["upward", "above", "raise", "ascend", "rise", "increase"],
  "off": ["away", "removed", "detached", "separate", "disconnected"],
  "under": ["below", "beneath", "underneath", "subordinate", "sub-"],
  "over": ["above", "across", "beyond", "throughout", "covering", "extra"],
  "such": ["like", "similar", "of that kind", "suchlike"],
  "more": ["additional", "extra", "further", "greater", "increased"],
  "less": ["fewer", "reduced", "smaller", "diminished", "lesser", "minus"],
  "most": ["greatest", "highest", "maximum", "utmost", "nearly all", "majority"],
  "few": ["several", "a few", "handful", "some", "a small number"],
  "several": ["multiple", "various", "numerous", "some", "a few"],
  "each": ["every", "all", "per", "apiece", "individually"],
  "every": ["each", "all", "every single", "whole", "entire"],
  "both": ["the two", "pair", "both sides", "mutually", "together"],
  "other": ["another", "different", "additional", "alternative", "distinct"],
  "another": ["other", "additional", "different", "further", "extra"],
  "own": ["personal", "private", "individual", "proprietary", "belonging"],
  "same": ["identical", "equal", "equivalent", "matching", "alike", "similar"],
  "such": ["like", "similar", "of that kind", "suchlike"],
  "much": ["a lot", "considerable", "great", "substantial", "significant"],
  "some": ["several", "a few", "certain", "various", "an amount of"],
  "any": ["some", "whatever", "whichever", "whosoever", "anyone", "either"],
  "no": ["none", "not any", "zero", "nothing", "negative"],
};

/* ------------------------------------------------------------------ */
/*  5.  Utilities                                                     */
/* ------------------------------------------------------------------ */

/**
 * Check if a word looks like a valid English word (case-insensitive).
 */
function isInDictionary(word) {
  return DICTIONARY.has(word.toLowerCase());
}

/**
 * Attempt to correct a single misspelled word.
 * Strategy (from safest to riskiest):
 *  1. If already in dictionary → return as-is
 *  2. Exact lookup in MISSPELLINGS map → known correction
 *  3. Transposition of adjacent letters (common typo)
 *  4. Single character insertion/removal (e.g. double letters)
 *  5. Otherwise → return original (better to keep the raw word than
 *     risk a false-positive correction)
 */
function correctWord(word) {
  const lower = word.toLowerCase();

  // 1. Already in dictionary or too short to correct
  if (isInDictionary(lower) || lower.length <= 2) return word;

  // 2. Exact misspelling map lookup
  if (MISSPELLINGS[lower]) return MISSPELLINGS[lower];

  // 3. Try swapping adjacent characters (transposition is ~20% of typos)
  for (let i = 0; i < lower.length - 1; i++) {
    const candidate = lower.slice(0, i) + lower[i + 1] + lower[i] + lower.slice(i + 2);
    if (isInDictionary(candidate) || MISSPELLINGS[candidate]) {
      return candidate;
    }
  }

  // 4. Try removing one character (catches double-letter typos like "harrry")
  for (let i = 1; i < lower.length - 1; i++) {
    const candidate = lower.slice(0, i) + lower.slice(i + 1);
    if (isInDictionary(candidate) || MISSPELLINGS[candidate]) {
      return candidate;
    }
  }

  // 5. Give up — return original word
  return word;
}

/**
 * Normalize contractions and abbreviations in text.
 */
function expandContractions(text) {
  let result = text;
  // Word-boundary replacement for contractions
  for (const [short, full] of Object.entries(CONTRACTIONS)) {
    const regex = new RegExp(`\\b${short}\\b`, "gi");
    result = result.replace(regex, full);
  }
  // Abbreviation expansion — uses a broader boundary pattern to handle
  // dotted abbreviations like "e.g." and "i.e."
  for (const [abbr, full] of Object.entries(ABBREVIATIONS)) {
    const escaped = abbr.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(`(^|[\\s(])${escaped}([\\s.,;!?)\\]\\-]|$)`, "gi");
    result = result.replace(regex, (_, before, after) => before + full + after);
  }
  return result;
}

/**
 * Expand a query with synonyms to improve semantic recall.
 * Appends `OR <synonym>` style phrases for the most significant content words.
 */
function expandSynonyms(text) {
  const words = text.split(/\s+/);
  const expanded = [];
  for (const word of words) {
    expanded.push(word);
    const lower = word.toLowerCase().replace(/^[^a-z]+|[^a-z]+$/g, "");
    const synonyms = SYNONYM_EXPANSIONS[lower];
    if (synonyms && synonyms.length > 0) {
      // Append the first 2 most common synonyms to the query
      // This enriches the token space for the embedding model
      expanded.push(synonyms.slice(0, 2).join(" "));
    }
  }
  return expanded.join(" ");
}

/* ------------------------------------------------------------------ */
/*  5.  Main pipeline                                                 */
/* ------------------------------------------------------------------ */

/**
 * Preprocess a user query before RAG retrieval.
 *
 * Pipeline:
 *  1. Normalize whitespace & punctuation
 *  2. Expand contractions     ("don't" → "do not")
 *  3. Expand abbreviations    ("e.g." → "for example")
 *  4. Spell-correct each word ("hary" → "harry", "beleive" → "believe")
 *  5. Expand synonyms         (adds related terms for the embedding model)
 *
 * @param {string} raw  Raw user question
 * @returns {{ cleaned: string, corrected: string, enriched: string }}
 *   - cleaned:   Contractions + abbreviations expanded
 *   - corrected: Same as cleaned, but with spelling corrected
 *   - enriched:  Ready-for-embedding version with synonym expansion
 */
function preprocessQuery(raw) {
  if (!raw || typeof raw !== "string") {
    return { cleaned: "", corrected: "", enriched: "" };
  }

  // Step 0: Trim & collapse whitespace
  let text = raw.trim().replace(/\s+/g, " ");

  // Step 1: Expand contractions & abbreviations
  text = expandContractions(text);

  const cleaned = text;

  // Step 2: Spell-correct each word
  const words = text.split(/\s+/);
  const correctedWords = words.map((w) => {
    // Preserve punctuation attached to words
    const m = w.match(/^([^a-zA-Z]*)([a-zA-Z].*[a-zA-Z])([^a-zA-Z]*)$/);
    if (!m) return w;
    const [, pre, core, post] = m;
    return pre + correctWord(core) + post;
  });
  const corrected = correctedWords.join(" ");

  // Step 3: Synonym enrichment for the embedding model
  const enriched = expandSynonyms(corrected);

  return { cleaned, corrected, enriched };
}

module.exports = { preprocessQuery, correctWord, expandContractions, expandSynonyms };